global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using CliWrap;
global using CliWrap.Buffered;
global using CSharpScriptOperations;
global using FileConversionTools.Operations;
